sudo: false
language: ruby
cache: bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - ruby-head
  - jruby
script: rspec spec && rubocop
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
    # NOTE: The tests never pass with 1.9.3 since WebMock stopped supporting 1.9.
    - rvm: 1.9.3
  fast_finish: true
